language: node_js
node_js:
  - 'node'
  - '12'
services:
  - mongodb
before_script:
  - cd back-end
  - npm install
  - mongo mydb_test --eval 'db.createUser({user:"user", pwd:"copply_password", roles:["readWrite"]});'
env:
  - MONGO_URI=mongodb+srv://user:copply_password@cluster0.gzhfd.mongodb.net/copply?retryWrites=true&w=majority
